<a href="https://colab.research.google.com/github/Motta99/Python/blob/main/Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Modelos


In [ ]:
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import sklearn.datasets as db 
import sklearn.model_selection as MS
import sklearn.metrics as metrics

from sklearn.datasets import fetch_openml
from sklearn.linear_model import SGDClassifier

## Classificação

In [ ]:
iris = db.load_iris()

In [ ]:
x, y, nomes = iris["data"], iris["target"], iris["target_names"]

In [ ]:
X_train, X_test, y_train, y_test =MS.train_test_split(x, y, test_size=0.30, random_state=42)

In [ ]:
SGD = SGDClassifier(random_state= 42)
SGD.fit(X_train, y_train)

SGDClassifier(random_state=42)

In [ ]:
SGD.predict(X_train)

array([1, 2, 2, 1, 2, 2, 2, 2, 0, 2, 1, 0, 0, 0, 1, 2, 0, 0, 0, 2, 0, 2,
       2, 0, 1, 2, 0, 2, 2, 1, 2, 2, 1, 0, 1, 2, 0, 0, 1, 2, 0, 2, 0, 0,
       2, 0, 2, 2, 2, 2, 2, 0, 0, 2, 2, 0, 0, 0, 2, 2, 0, 2, 2, 0, 2, 2,
       2, 1, 2, 0, 2, 2, 2, 1, 2, 2, 0, 1, 2, 0, 2, 2, 2, 0, 1, 2, 2, 0,
       2, 0, 2, 2, 2, 2, 2, 1, 1, 2, 2, 0, 1, 2, 0, 1, 2])

In [ ]:
y_test

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0])

### Metodos de Avaliação do modelo

In [ ]:
#Metodos de Avaliação do modelo
"""cv determina a quantidade de vezes que o nosso modelo será dividido, após isso ele aplicará o método de avaliação escrito
em scoring (accuracy) e retornará o desempenho baseado nisso"""
MS.cross_val_score(SGD, X_train, y_train, cv=3, scoring="accuracy")

#metrics.SCORERS.keys() -- Métricas

array([0.88571429, 0.91428571, 0.97142857])

In [ ]:
#Matriz confusão

y_train_pred = MS.cross_val_predict(SGD, X_train, y_train, cv=3)
confusao_iris = metrics.confusion_matrix(y_train, y_train_pred)


#Precisão
precisao_iris = metrics.precision_score(y_train, y_train_pred, average="micro")

#Recall / Revocação
recall_iris = metrics.recall_score(y_train, y_train_pred, average="micro")

#F1 score
f1_iris = metrics.f1_score(y_train, y_train_pred, average="micro")

print(f'Matriz Confusão: \n{confusao_iris} \n\nPrecisão: {precisao_iris} \n\nRecall: {recall_iris} \n\nF1: {f1_iris}')


Matriz Confusão: 
[[31  0  0]
 [ 1 33  3]
 [ 0  4 33]] 

Precisão: 0.9238095238095239 

Recall: 0.9238095238095239 

F1: 0.9238095238095239


In [ ]:
#Breast Cancer Classificação Binária

#Preparando a base de dados
cancer = db.load_breast_cancer()
x_cancer, y_cancer, nomes_cancer = cancer["data"], cancer["target"], cancer["target_names"]

#Separando o conjunto de treino e teste
X_train_cancer, X_test_cancer, y_train_cancer, y_test_cancer = MS.train_test_split(x, y, test_size=0.30, random_state=42)

#Chamando o método de classificação
SGD_cancer = SGDClassifier(random_state= 42)
SGD_cancer.fit(X_train_cancer, y_train_cancer)

#acurácia do modelo
acuracia_cancer = MS.cross_val_score(SGD, X_train, y_train, cv=3, scoring="accuracy")

#previsão
y_train_cancer_pred = MS.cross_val_predict(SGD, X_train_cancer, y_train_cancer, cv=3)

#Matriz Confusão
confusao_cancer = metrics.confusion_matrix(y_train_cancer, y_train_cancer_pred)

#Precisão
precisao_cancer = metrics.precision_score(y_train_cancer, y_train_cancer_pred, average="micro")

#Recall / Revocação
recall_cancer = metrics.recall_score(y_train_cancer, y_train_cancer_pred, average="micro")

#F1 score
f1_cancer = metrics.f1_score(y_train_cancer, y_train_cancer_pred, average="micro")

print(f'Acurácia: {acuracia_cancer} \n\nMatriz Confusão: \n{confusao_cancer} \n\nPrecisão: {precisao_cancer} \n\nRecall: {recall_cancer} \n\nF1: {f1_cancer}')

Acurácia: [0.88571429 0.91428571 0.97142857] 

Matriz Confusão: 
[[31  0  0]
 [ 1 33  3]
 [ 0  4 33]] 

Precisão: 0.9238095238095239 

Recall: 0.9238095238095239 

F1: 0.9238095238095239


In [ ]:
y_cr = (y_cancer == 1)
y_cr

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False, False, False, False,
       False,  True, False,  True,  True,  True,  True,  True, False,
       False,  True, False, False,  True,  True,  True,  True, False,
        True, False, False,  True,  True,  True,  True, False,  True,
       False, False,  True, False,  True, False, False,  True,  True,
        True, False, False,  True, False, False, False,  True,  True,
        True, False,  True,  True, False, False,  True,  True,  True,
       False, False,  True,  True,  True,  True, False,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False,  True, False, False,  True,  True,  True,
       False, False,